const books = [
  {
    id: 1,
    title: "All Good People Here: A Novel",
    category: "crime",
    author: "Ashley Flowers",
    price: 49.06,
    img: "https://m.media-amazon.com/images/I/81XQ1+piiiL._AC_UL320_.jpg",
    desc: "#1 NEW YORK TIMES BESTSELLER • In the propulsive debut novel from the host of the #1 true crime podcast Crime Junkie, a journalist uncovers her hometown's dark secrets when she becomes obsessed with the unsolved murder of her childhood neighbor—and the disappearance of another girl twenty years later.",
  },
  {
    id: 2,
    title: "How to Be a Rock Star",
    category: "kids",
    author: "Lisa Tolin & Daniel Duncan",
    price: 19.99,
    img: "https://m.media-amazon.com/images/I/A1Ks4xjIdiL._AC_UL320_.jpg",
    desc: "In this hilarious, tongue-in-cheek picture book debut, one little kid who really loves to rock and roll explains everything there is to know about starting a rock band. 'A joyous, raucous must-have manual for little rock stars everywhere.' —Savannah Guthrie, Today show co-anchor",
  },
  {
    id: 3,
    title: "The Pigeon Will Ride the Roller Coaster!",
    category: "kids",
    author: "Mo Willems",
    price: 6.99,
    img: "https://m.media-amazon.com/images/I/716pwwt36NL._AC_UY218_.jpg",
    desc: "From #1 New York Times best-selling, award-winning author and illustrator Mo Willems! Buckle up for twists, turns, and emotional loop-de-loops in the most roller coaster-y Pigeon book ever! The Pigeon WILL be ready. Will YOU!?",
  },
  {
    id: 4,
    title:
      "The Second World Wars: How the First Global Conflict Was Fought and Won",
    category: "history",
    author: "Victor Davis Hanson",
    price: 17.89,
    img: "https://m.media-amazon.com/images/I/81J7E7-hqUL._AC_UY218_.jpg",
    desc: "A 'breathtakingly magisterial' account of World War II by America's preeminent military historian (Wall Street Journal). World War II was the most lethal conflict in human history. Never before had a war been fought on so many diverse landscapes and in so many different ways, from rocket attacks in London to jungle fighting in Burma to armor strikes in Libya.",
  },
  {
    id: 5,
    title: "The American Revolution: A Visual History",
    category: "history",
    author: "DK",
    price: 33.56,
    img: "https://m.media-amazon.com/images/I/91EKaSEqhlL._AC_UY218_.jpg",
    desc: "Uncover the remarkable story of the American Revolution! Who were the Redcoats, and what was the Boston Tea Party? Explore key events like the British surrender at Yorktown, and the writing of the Declaration of Independence. Written in association with the esteemed Smithsonian Institution, this beautiful visual reference book will transport you back in time and onto the front lines of the American Revolution.",
  },
  {
    id: 6,
    title: "Food: What the Heck Should I Eat?",
    category: "food",
    author: "Mark Hyman M.D.",
    price: 18.99,
    img: "https://m.media-amazon.com/images/I/81F4aVFGDWL._AC_UY218_.jpg",
    desc: "#1 New York Times bestselling author Dr. Mark Hyman sorts through the conflicting research on food to give us the skinny on what to eat. Did you know that eating oatmeal actually isn't a healthy way to start the day? That milk doesn't build bones, and eggs aren't the devil?",
  },
  {
    id: 7,
    title: "Devil's Food Cake Murder",
    category: "food",
    author: "Joanne Fluke",
    price: 8.99,
    img: "https://m.media-amazon.com/images/I/81m-JSczPSL._AC_UY218_.jpg",
    desc: "USA Today Bestseller: A minister, a mynah bird, and a murder keep a sleuthing baker busy in this “fabulous” mystery with “mouthwatering recipes” (Publishers Weekly). Hannah Swensen has to admit life is pretty sweet. Things are going well in the romance department, and her bakery's delectable confections are selling as fast as she can make them. Even her good friend Claire is head over heels with her new husband, Reverend Bob Knudson. If only they could find time to take their honeymoon!",
  },
  {
    id: 8,
    title: "Bittersweet Memories",
    category: "romance",
    author: "Catharina Maura",
    price: 14.99,
    img: "https://m.media-amazon.com/images/I/71Oixw7RidL._AC_UY218_.jpg",
    desc: "When her boyfriend breaks her heart, Alanna goes after his older brother in a quest for revenge. It would have been simple — if he wasn't also her new boss. As they work together it soon becomes clear Silas knows more about her than he should. He knows about the past she's forgotten and the memories that evade her... but some secrets are better left buried.",
  },
  {
    id: 9,
    title: "Caged Thorn",
    category: "romance",
    author: "Naomi West",
    price: 19.99,
    img: "https://m.media-amazon.com/images/I/81F9zDYA2DL._AC_UL320_.jpg",
    desc: "Ten years ago, I ran from my home. Today, I'm running back. The difference this time is that my son is coming with me. We're going back to the place I swore I'd never return to. Back to the lies and the heartbreaks and the site of the day that changed my life forever.",
  },
];
export default books;
